# Generated by Django 5.0.1 on 2024-04-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relabel_Detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='product_model',
            field=models.CharField(default='TR', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labelhistory',
            name='label_images',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='check_pass',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='labeled',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='trained',
            field=models.BooleanField(),
        ),
    ]
