# Generated by Django 5.0.1 on 2024-04-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relabel_Detection', '0002_detectionhistory_product_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelhistory',
            name='log_path',
            field=models.CharField(default='logs/init', max_length=100),
            preserve_default=False,
        ),
    ]
