# Generated by Django 5.0.1 on 2024-04-26 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relabel_Detection', '0004_remove_detectionhistory_check_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confighistory',
            name='change_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 14, 40, 8, 742184)),
        ),
        migrations.AlterField(
            model_name='confighistory',
            name='changes',
            field=models.TextField(default='无任何修改'),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 14, 40, 8, 742184)),
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='image_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 14, 40, 8, 726822)),
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='image_path',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='labeled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labelhistory',
            name='label_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 14, 40, 8, 742184)),
        ),
        migrations.AlterField(
            model_name='labelhistory',
            name='label_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelhistory',
            name='log_path',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modelhistory',
            name='model_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 14, 40, 8, 742184)),
        ),
        migrations.AlterField(
            model_name='modelhistory',
            name='onnx_path',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modelhistory',
            name='pt_path',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videohistory',
            name='video_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 14, 40, 8, 741184)),
        ),
        migrations.AlterField(
            model_name='videohistory',
            name='video_path',
            field=models.CharField(max_length=50),
        ),
    ]
