# Generated by Django 5.0.1 on 2024-04-26 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relabel_Detection', '0006_alter_confighistory_change_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confighistory',
            name='change_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 6, 50, 50, 371830, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 6, 50, 50, 371830, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='image_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 6, 50, 50, 355060, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='labelhistory',
            name='label_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 6, 50, 50, 371830, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='modelhistory',
            name='model_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 6, 50, 50, 371830, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='videohistory',
            name='video_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 6, 50, 50, 370831, tzinfo=datetime.timezone.utc)),
        ),
    ]
