# Generated by Django 5.0.1 on 2024-05-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relabel_Detection', '0009_alter_confighistory_change_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confighistory',
            name='change_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='image_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='labelhistory',
            name='label_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='modelhistory',
            name='model_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='videohistory',
            name='video_date',
            field=models.DateTimeField(),
        ),
    ]
